# Generated by Django 3.1.1 on 2020-10-05 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
    ]
